language: node_js

node_js:
    - 15.2.1

npm:
    - 7.0.10

cache:
  directories:
    - node_modules

install:
    npm install

script:
    - npm run build:js
    - npm run build:css
    - npm run test -- --maxWorkers=2
    - npm run lint

notifications:
  email: false
