# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: yarn

    - name: Build backend [Golang]
      run: yarn build --ci server

    - name: Build frontend [TypeScript]
      run: yarn build --ci --prod digital

    - name: Run tests (App) [TypeScript]
      run: yarn test  --ci app

    - name: Build docs
      run: |
        yarn build:jsdocs
        yarn build:docs
  
  server-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run coverage
      run: cd src/server && go test ./... -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      run: cd src/server && bash <(curl -s https://codecov.io/bash)
