name: Build and Deploy to GAE for update-to-date builds
env:
  CLOUDSDK_CORE_PROJECT: opencircuits-nightly

on:
  push:
    branches:
    - master

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Set Node.js 15.x
      uses: actions/setup-node@master
      with:
        node-version: 15.x

    - name: Install
      run: npm install

    - name: Build
      run: npm run build -- --ci server digital

    - name: Create OAuth credentials and app.yaml
      run: |
        mkdir -p ./site/secrets
        echo "${{ secrets.OAUTH_CREDENTIALS }}" >> ./site/secrets/credentials.json
        echo "${{ secrets.APP_YAML }}" >> app.yaml

    - name: Deploy
      working-directory: ./build
      run: gcloud app deploy --quiet

